### ISSUE TITLE
install problem using composer

### ISSUE THREAD

**Issue by horaciod** [MARCspec/File_MARC_Reference#1]
Hello: 
I'm having problems installing via composer. 
message : 
"Problem 1
    - Installation request for ck/file_marc_reference dev-master -> satisfiable by ck/file_marc_reference[dev-master].
    - ck/file_marc_reference dev-master requires ck/php-marcspec dev-master -> no matching package found."
I think that the problem is with php-marcspec package, only 1.5 version is installable and available (not dev-master).
how can i solve this problem,

**Comment by cKlee** [comment]
Stability flag was set via https://github.com/MARCspec/File_MARC_Reference/commit/c8751985730a7442d17421e3e35a11c194f97b3f 
Should install now without problems. Right?
